### PR TITLE
Add editor plugins for YAML/MD/GraphViz

### PR DESCRIPTION
**Pull request by Apanatshka**
Tested and working. Small change, but I figure @Gohla will want to review this since I'm messing with the build code.

### CODE REVIEW

**Comment by Apanatshka** [comment]
Oh, I only tried `./b build all` followed by `./b gen-spoofax -d ~/eclipse/spoofax-dev`. I'll try that command you mentioned now.

**Comment by Apanatshka** [comment]
Hmm, doesn't work. Trying to download [JRE 8 for Windows](http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jre-8u152-windows-x64.tar.gz) fails.

**Comment by Apanatshka** [comment]
So, the problem is that the Python library `eclipse-gen` tries to download JREs that are no longer hosted on OTN. Our buildfarm doesn't run into problems because it's not stateless and eclipse-gen caches the JRE downloads on the filesystem. But on my machine I cannot reproduce builds with built-in JREs since the eclipse-gen dependency has hardcoded URLs where it gets the JREs.

**Comment by Gohla** [comment]
I see. The URL is hardcoded here: https://github.com/Gohla/eclipsegen/blob/master/eclipsegen/generate.py#L339. If you make a PR there I can release a new version of eclipsegen.

**Comment by Apanatshka** [comment]
PR made: https://github.com/Gohla/eclipsegen/pull/1

**Comment by Gohla** [comment]
New eclipsegen is deployed and used in master, so you should be able to test Eclipse generation (and testing to see if Spoofax works in it) now.

**Comment by Apanatshka** [comment]
That took a while, but `./b build -e eclipse-instances` finished successfully 🙂

**Comment by Gohla** [comment]
Thanks! 👍

**Pull request merged**
